CREATE DATABASE IF NOT EXISTS alumnos;

USE alumnos;


CREATE TABLE IF NOT EXISTS alumno(
ida INT NOT NULL UNIQUE AUTO_INCREMENT,
nombre VARCHAR(30) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
rut VARCHAR(13) NOT NULL,
curso VARCHAR(200) NOT NULL,
PRIMARY KEY(ida)
)ENGINE=INNODB;





