CREATE DATABASE IF NOT EXISTS alumnos;

USE alumnos;


CREATE TABLE IF NOT EXISTS alumno(
rut VARCHAR(12) NOT NULL UNIQUE,
nombre VARCHAR(30) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
curso VARCHAR(200) NOT NULL,
PRIMARY KEY(rut)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS grupos(
id INT NOT NULL AUTO_INCREMENT, 
nombre VARCHAR(30) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
grupo VARCHAR(50) NOT NULL,
rol VARCHAR(30) NOT NULL,
PRIMARY KEY(id),
rut VARCHAR(12) NOT NULL UNIQUE,
CONSTRAINT fkgrupos_alumno
FOREIGN KEY(rut) REFERENCES alumno(rut)
)ENGINE=INNODB;