CREATE DATABASE IF NOT EXISTS grupos;

USE grupos;


CREATE TABLE IF NOT EXISTS grupos(
id INT NOT NULL AUTO_INCREMENT, 
nombre VARCHAR(30) NOT NULL,
apellidos VARCHAR(30) NOT NULL,
rut VARCHAR(12) NOT NULL UNIQUE,
grupo VARCHAR(50) NOT NULL,
rol VARCHAR(30) NOT NULL,
chequeo VARCHAR(30) NOT NULL,
PRIMARY KEY(id)
)ENGINE=INNODB;
